### ISSUE TITLE
mouse scrolling to adjust knobs

### ISSUE THREAD

**Issue by Be-ing** [harryhaaren/openAV-Luppp#100]
The only way to adjust knob controls on the GUI without a controller is by holding a click and dragging. This is not a very easy way to control a knob. It would be nice to be able to adjust knobs by holding the cursor over them and scrolling like Mixxx.

**Comment by harryhaaren** [comment]
Hi @Be-ing, 

I totally agree here - actually even stronger - almost every interaction should be scroll-wheel, right click, left click, left click + drag "friendly". To this end, OpenAV is writing AVTK, a toolkit which explicitly supports "advanced" controls like scroll wheel over any control etc.
http://www.openavproductions.com/avtk/

AVTK will be released in the next 2 weeks, along with some other projects.

I do not think Luppp will be re-written in AVTK in the short term - there are bigger things to handle. Stay tuned, OpenAV is planning on releasing its work of the last few months and coming plans soon.

Thanks for the feature-request - unfortunatly I don't think this is going to be fixed soon, sorry. Thanks again, -Harry

**Comment by Be-ing** [comment]
Good to hear. Since you are making such a comprehensive change, have you thought about touch screen support? Will rewriting Luppp with AVTK make it usable on tablets without a controller?

**Comment by harryhaaren** [comment]
AVTK uses the PUGL library for input / events, and on its current platforms there is no multi-touch support. Note that I'm not planning on re-writing Luppp - there is another project that will be announced soon to superseed the Luppp project, for both technical and workflow reasons.
