### ISSUE TITLE
Segmentation Fault on Run

### ISSUE THREAD

**Issue by htmlguy** [harryhaaren/openAV-Luppp#104]
I just compiled luppp as instructed in the README, on the `release-1.0.1` branch, and got the following messages when I try to run it:
```
main:63: Git: d75ca04 -Removed extra prints
Gui:336: Gui()
Gui:457: Loaded preferences
Gui:483: No session management in use
Segmentation fault (core dumped)
```
I just installed `ntk` from it's git repository as listed, and although it worked, I got a few warnings during the build, so I think a bad `ntk` build might be the issue.

There were no errors when building luppp.
I am running Trisquel GNU/Linux (Based off ubuntu.)

**Comment by harryhaaren** [comment]
Hi @htmlguy,

I don't think its an NTK issue - if it compiles OK it should be ok..

Is JACK already running before you start Luppp? That might be a possible cause.

Could you paste the output of the following command too please?
```
jackd --version
```

Cheers, -Harry

**Comment by htmlguy** [comment]
Thanks, I forgot to install that - I installed libjack-dev but not jackd.

**Comment by harryhaaren** [comment]
Thanks for reporting back and closing, appreciated! -Harry
