### ISSUE TITLE
Compilation on Raspberry Pi 2

### ISSUE THREAD

**Issue by harryhaaren** [harryhaaren/openAV-Luppp#106]
As reported by @TDeagan via email:
```
cc1plus: error: unrecognized command line option ‘-msse2’
cc1plus: error: unrecognized command line option ‘-mfpmath=sse’
make[2]: *** [src/CMakeFiles/luppp.dir/metronome.cxx.o] Error 1
make[2]: *** Waiting for unfinished jobs....
cc1plus: error: unrecognized command line option ‘-msse2’
cc1plus: error: unrecognized command line option ‘-mfpmath=sse’
make[2]: *** [src/CMakeFiles/luppp.dir/looperclip.cxx.o] Error 1
make[1]: *** [src/CMakeFiles/luppp.dir/all] Error 2

It appears that those options are related to Intel and AMD processor capabilities.
Is Luppp only supported on those procs?  Do you think I have any hope of running it on an RPi 2?
```

**Comment by harryhaaren** [comment]
Hi Tim,

Grab the latest from Git (see commit above) and it will hopefully pass - I don't have an RPi here to quickly test on - if my guessing is correct, this should be fixed though.

Thanks for reporting, -Harry

**Comment by TDeagan** [comment]
Sweet!  Code built with only a few warnings, run.sh resulted in a copy of Luppp fitting exactly into my 7" touchscreen on my Raspberry Pi 2 (Raspbian Wheezy)

Thanks for the quick fix!!  I'l start loading up some clips and see how it runs.

Cheers,
--Tim

**Comment by harryhaaren** [comment]
Thanks for the report back, I'll mark this issue as closed. Cheers!
