### ISSUE TITLE
Sequencer view?

### ISSUE THREAD

**Issue by naught101** [harryhaaren/openAV-Luppp#80]
This is not a feature request, so much as a question about where Luppp is heading. Are you planning to eventually add something like a sequencer view, so that sequences of loop combinations can be recorded, played back, and manipulated?

**Comment by harryhaaren** [comment]
Hi @goncalopp,

For some reason I missed your comment - and never replied (yet). Sorry about that. I guess a response now is better than not one at all.

- The main issue with JACK apps is that when there's a "loopback" from a client's outputs to its inputs, it creates an additional "nframes" of delay. This actually means that a mixer as you've suggested (and the modular approach in general) is not ideal for live performance, as it increases latency artificially, by providing modular features usually the "power-users" wish for.

- For me the most interesting question about Luppp / seqeuncing / MIDI looping etc is not what *can* be done, but what is actually *worth doing*. To draw an analogy, the DX7 synth limited the user to a fixed set of FM algorithm setups. This led to people learning to use them extensively, and making music with them. I feel that the modular setup is somewhat the opposite of this - with infinite routing options, I get lots in possibilities of FX racks etc, and forget to actually make music.

- Bringing this analogy to stage, I am in search of the optimal balance between flexibility and ideal workflow. On-stage use demands an efficient workflow, and hence that takes priority over flexibility for me..

- In terms of the codebase, its pretty modularly designed, and it certainly could be done. For me, LV2 plugins are currently more interesting as then the programs can be used "genuinely" modular (inside modular LV2 hosts like Ingen[1]).

Again, apologies for missing your post, any questions don't hesitate to ask. Cheers, -Harry

[1] http://drobilla.net/software/ingen/

**Comment by harryhaaren** [comment]
Luppp will not be getting enough development time to build a sequencer view - the focus of OpenAV has shifted to LV2 plugins, allowing use with the MOD platform.

Thanks for your input and ideas, I have re-read this thread, and will be including your input in the design and implementation of "Buska", a looping LV2 plugin that will replace Luppp as it also has a  live-looping workflow.

Marking this as closed, as I'm cleaning up the issue tracker. Cheers, -Harry
