### ISSUE TITLE
feature request: multichannel loops

### ISSUE THREAD

**Issue by magnetophon** [harryhaaren/openAV-Luppp#84]
As a first step, you could keep the internal mixer mono, and just have the extra outs on the individual loop outputs, to be mixed in an external program.

**Comment by harryhaaren** [comment]
The in-development "Buska" project by OpenAV includes stereo loops. Luppp will not get developed to incorperate true multi-channel loops, sorry.

I'm cleaning up the Luppp issue tracker, so marking as closed. Thanks, -Harry
