### ISSUE TITLE
Bidings input & outpout requires 2 different buttons nanopad

### ISSUE THREAD

**Issue by slyholborn** [harryhaaren/openAV-Luppp#97]
Hello, thanks for the work and sorry for my english which isn't my native language. When i want to configure my midi pads (nano kontrol and nano pad2) it's impossible to on/off fonctions with the same button of my pads. Knobs and slides are working good, so i don't think it's a midi issue. 

{
	"name":	"test",
	"author":	"",
	"link":	"",
	"inputBindings":	[{
			"action":	"track:send_active",
			"status":	144,
			"data":	37,
			"track":	0,
			"send":	0,
			"active":	1
		}, {
			"action":	"track:send_active",
			"status":	144,
			"data":	36,
			"track":	0,
			"send":	0,
			"active":	0
		}]
}

Thanks for watching!

**Comment by harryhaaren** [comment]
Hi @slyholborn, 

Do you want to momentary or toggle the Send?
Momentary is easily possible, see script below.

For toggle behaviour, most MIDI controllers can edit their behaviour, to be like this:
- button press #1 becomes note-on event
- button press #2 becomes note off
The script below then works for this type of MIDI note on / off sending, but has a toggle effect.

Editing the Nano can be done using Linux Native tool called [NanoBasket](https://github.com/royvegard/Nano-Basket), and the Windows editor apparently runs in Wine for the other..

Hope that helps, cheers, -Harry

The following .ctlr script turns on / off based on a single note:
```
{
        "name": "MidiNoteOnOff",
        "author":       "OpenAV",
        "link": "https://github.com/harryhaaren/openAV-Luppp/issues/97",
        "inputBindings":        [{
                        "action":       "track:send_active",
                        "status":       144,
                        "data": 36,
                        "track":        0,
                        "send": 0,
                        "active":       1
                }, {
                        "action":       "track:send_active",
                        "status":       128,
                        "data": 36,
                        "track":        0,
                        "send": 0,
                        "active":       0
                }]
}
```

**Comment by slyholborn** [comment]
Thanks! i try to edit the behaviour of my nano!

**Comment by slyholborn** [comment]
Works fine with toggling pads, thanks a lot! Still can't make nano basket work or the kork on via wine work, but i kept dual boot for those issues so...

**Comment by harryhaaren** [comment]
Thanks for reporting back, glad the Luppp bindings are working well.

Perhaps file an issue on [the nanobased page](https://github.com/royvegard/Nano-Basket/issues/new) for whatever issue you're having.

Cheers, -Harry
