### ISSUE TITLE
Track 1, 4, and 8 Fader issue

### ISSUE THREAD

**Issue by dsreyes1014** [harryhaaren/openAV-Luppp#99]
I have an issue with faders on track 1,4, and 8.  The fader will move sideways only with a fader that's the length of the container (unusual) vs a small rectangle that I can move up and down to control volume.

**Comment by harryhaaren** [comment]
Hey @dsreyes1014, 

I gather you experience that the faders on tracks 1,4,8 move horizontally instead of vertically? Is that correct?

I can't reproduce this issue, could you describe it in more detail please? Perhaps with a screenshot if that would help?

**Comment by dsreyes1014** [comment]
Here is a screenshot:

![screenshot from 2015-03-25 22-19-58](https://cloud.githubusercontent.com/assets/2116998/6839882/6677c5f6-d33d-11e4-801f-2015f3c31e20.png)

**Comment by harryhaaren** [comment]
Thanks that confirms the issue - I'll fix this later today - its a strange bug that I don't experience, but I think i know what is causing it. Thanks for the screenshot, -Harry

**Comment by dsreyes1014** [comment]
Update:  I finally used the program this weekend at my church for our music and all went ok.  It seems the metronome drifts a bit but that's a separate issue.  As far as the faders,  I'm using Gnome 3.16 and your program seems to render better on Wayland than it does on X.  When logging into Wayland the only fader that has the issue is fader 6.  When logging into an X session it's the same as the attached image from my second post which is faders 1, 4, and 8.

**Comment by dsreyes1014** [comment]
Any update on this bug?

**Comment by harryhaaren** [comment]
Hi,
Admittedly I had forgotten about this - apologies. I've just reproduced the issue, going to look at the code now - will report back shortly.
Cheers, -Harry

**Comment by harryhaaren** [comment]
@dsreyes1014, it was an easy fix, that's good news I guess. Id like to fix #96, and then I'll do a bugfix release.
Note that "Buska" (the next gen looping solution) is under heavy development - and will replace Luppp eventually.
